stages:
  - test

test-job:
  stage: test
  image: ubuntu:22.04
  script:
    - echo "Running tests..."
    - ./success.sh
    - exit 1  # 失敗をシミュレート
  retry:
    max: 2  # 最大2回まで再実行
  after_script:
    - ./.failed.sh