stages:
  - unit-test

unit-test-result-web:
  stage: unit-test
  script:
    - mkdir -p unit-test/web
    - echo "unit-test-result-web" >> unit-test/unit-test-result-web.txt
  artifacts:
    paths:
      - unit-test/